version: 2
jobs:
  build:
    working_directory: /mnt/www
    docker:
      - image: validator/validator:latest

    steps:
      - checkout

      - run:
          name: validate my html
          command: vnu /mnt/www/

workflows:
  version: 2
  build-verify:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - /no-build/.*
